name: audl
version: 1.0
profile: audl-postgres


model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  audl:
    load:
      +schema: load
      +materialized: table
    staging: 
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

