CREATE TABLE IF NOT EXISTS game_metadata (
    id INT PRIMARY KEY,
    team_season_id_home INT NOT NULL,
    team_season_id_away INT NOT NULL,
    status_id INT,
    score_home INT,
    score_away INT,
    live BOOLEAN,
    reg_season BOOLEAN,
    ignore_game BOOLEAN,
    lock BOOLEAN,
    start_timestamp TIMESTAMP,
    start_timezone TEXT,
    start_time_tbd BOOLEAN,
    aw_section TEXT,
    score_times_home TEXT,
    score_times_away TEXT,
    ext_game_id TEXT NOT NULL,
    update_timestamp TIMESTAMP,
    location_id INT,
    ls_game_id TEXT,
    ticket_url TEXT,
    streaming_url TEXT,
    roster_set BOOLEAN,
    roster_set_1 BOOLEAN,
    type_id INT,

    -- Flattened team_season_home
    team_season_home_id INT,
    team_season_home_team_id INT,
    team_season_home_season_id INT,
    team_season_home_division_id INT,
    team_season_home_city TEXT,
    team_season_home_abbrev TEXT,
    team_season_home_ulti_analytics_ext_id TEXT,
    team_season_home_final_standing INT,
    team_season_home_team_name TEXT,
    team_season_home_team_ext_team_id TEXT,
    team_season_home_team_ls_team_id TEXT,
    team_season_home_team_active BOOLEAN,
    team_season_home_team_primary_hex TEXT,
    team_season_home_team_secondary_hex TEXT,

    -- Flattened team_season_away
    team_season_away_id INT,
    team_season_away_team_id INT,
    team_season_away_season_id INT,
    team_season_away_division_id INT,
    team_season_away_city TEXT,
    team_season_away_abbrev TEXT,
    team_season_away_ulti_analytics_ext_id TEXT,
    team_season_away_final_standing INT,
    team_season_away_team_name TEXT,
    team_season_away_team_ext_team_id TEXT,
    team_season_away_team_ls_team_id TEXT,
    team_season_away_team_active BOOLEAN,
    team_season_away_team_primary_hex TEXT,
    team_season_away_team_secondary_hex TEXT
);
