CREATE TABLE IF NOT EXISTS game_metadata (
    id INT PRIMARY KEY,
    team_season_id_home INT NOT NULL,
    team_season_id_away INT NOT NULL,
    status_id INT,
    score_home TINYINT,
    score_away TINYINT,
    live BOOLEAN,
    reg_season BOOLEAN,
    ignore_game BOOLEAN,
    lock BOOLEAN,
    start_timestamp TIMESTAMP,
    start_timezone TINYTEXT,
    start_time_tbd TIMESTAMP,
    aw_section TINYTEXT,
    score_times_home INT,
    score_times_away INT,
    ext_game_id TINYTEXT NOT NULL,
    update_timestamp TIMESTAMP,
    location_id INT,
    ls_game_id TINYTEXT,
    ticket_url TINYTEXT,
    streaming_url TINYTEXT,
    roster_set BOOLEAN,
    roster_set_1 BOOLEAN,
    type_id TINYINT,
    team_season_home.id INT,
    team_season_home.team_id INT,
    team_season_home.season_id INT,
    team_season_home.division_id INT,
    team_season_home.city TINYTEXT,
    team_season_home.abbrev TINYTEXT,
    team_season_home.ulti_analytics_ext_id TINYTEXT,
    team_season_home.final_standing TINYINT,
    team_season_home.team.id INT,
    team_season_home.team.name TINYTEXT,
    team_season_home.team.ext_team_id TINYTEXT,
    team_season_home.team.ls_team_id TINYTEXT,
    team_season_home.team.active BOOLEAN,
    team_season_home.team.primary_hex TINYTEXT,
    team_season_home.team.secondary_hex TINYTEXT,
    team_season_away.id INT,
    team_season_away.team_id INT,
    team_season_away.season_id INT,
    team_season_away.division_id INT,
    team_season_away.city TINYTEXT,
    team_season_away.abbrev TINYTEXT,
    team_season_away.ulti_analytics_ext_id TINYTEXT,
    team_season_away.final_standing TINYINT,
    team_season_away.team.id INT,
    team_season_away.team.name TINYTEXT,
    team_season_away.team.ext_team_id TINYTEXT,
    team_season_away.team.ls_team_id TINYTEXT,
    team_season_away.team.active BOOLEAN,
    team_season_away.team.primary_hex TINYTEXT,
    team_season_away.team.secondary_hex TINYTEXT,
);
