version: 2
sources:
  - name: raw
    meta:
      external_location: "read_json_auto('{{ env_var('AUDL_SOURCE_DIR') }}/{name}/*/*.json', hive_partitioning=true, union_by_name=true)"
    tables:
      - name: games
      - name: players
      - name: teams
  - name: processed
    meta:
      external_location: "read_json_auto('{{ env_var('AUDL_PROCESSED_DIR') }}/{name}/**/*.json', hive_partitioning=true, union_by_name=true)"
    tables:
      - name: ext_blocks
      - name: ext_games
      - name: ext_point_lineups
      - name: ext_pulls
      - name: ext_throws
