CREATE TABLE player_stats_cumulated (
    user_id INT,
    date DATE, 
    last30_assists INT[],
    last30_goals INT[],
    last30_hockey_assists INT[],
    last30_completions INT[],
    last30_throwaways INT[],
    last30_stalls INT[],
    last30_throws_attempted INT[],
    last30_catches INT[],
    last30_drops INT[],
    last30_blocks INT[],
    last30_callahans INT[],
    last30_pulls INT[],
    last30_out_of_bound_pulls INT[],
    last30_recorded_pulls INT[],
    last30_recorded_pulls_hang_time INT[],
    last30_offensive_points_played INT[],
    last30_offensive_points_scored INT[],
    last30_defensive_points_played INT[],
    last30_defensive_points_scored INT[],
    last30_seconds_played INT[],
    last30_yards_received INT[],
    last30_yards_thrown INT[],
    last30_hucks_completed INT[],
    last30_hucks_attempted INT[],
    PRIMARY KEY (user_id, ext_game_id)
)
