CREATE TABLE IF NOT EXISTS load_game_tsg (
    id INT PRIMARY KEY,
    teamSeasonId INT,
    gameId INT,
    source TEXT,
    startOnOffense BOOLEAN,
    events TEXT,
    updateMoment TIMESTAMP,
    statusId INT,
    scoreTimesOur TEXT,
    scoreTimesTheir TEXT,
    completionsNumer INT,
    completionsDenom INT,
    hucksNumer INT,
    hucksDenom INT,
    blocks INT,
    turnovers INT,
    oLineScores INT,
    oLinePoints INT,
    oLinePossessions INT,
    dLineScores INT,
    dLinePoints INT,
    dLinePossessions INT,
    redZoneScores INT,
    redZonePossessions INT,
    isHome BOOLEAN,
    rosterIds TEXT
);
